// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ycmevodthpixhqoahawv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljbWV2b2R0aHBpeGhxb2FoYXd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzczOTA3MTQsImV4cCI6MjA1Mjk2NjcxNH0.9VJs-CAfpvlaAMh0UVcR1dc2HQmQVsE-jSvFnn_9Nt8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);